---
# tasks file for chriswayg.lxctemplate

- name: Remove Enterprise Repo
  apt_repository:
    repo: 'deb https://enterprise.proxmox.com/debian stretch pve-enterprise'
    state: absent

- name: Add Community Repo
  apt_repository:
    repo: 'deb http://download.proxmox.com/debian stretch pve-no-subscription'
    state: present

- name: Include maketemplate.yml
  include_tasks: maketemplate.yml
  when: lxctemplate_make

- name: Include container.yml
  include_tasks: container.yml
  when: lxctemplate_container
