---
# tasks file for chriswayg.lxctemplate

- name: Install Debian Appliance Builder (DAB)
  apt:
    pkg: dab
    update_cache: yes
    state: installed

- name: Create a build directory
  file: 
    path: "{{ lxctemplate_builds }}/{{ lxctemplate_dir }}"
    state: directory
  register: build_dir

- name: Upload dab.conf from template
  template:
    src: dab.conf.j2
    dest: "{{ lxctemplate_builds }}/{{ lxctemplate_dir }}/dab.conf"
  register: conf

- name: Include lnitialize_template.yml
  include_tasks: initialize_template.yml
  when: build_dir.changed or conf.changed

